apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pvc
  resources:
    requests:
      storage: 2Gi