apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2  # Nombre de pods à déployer
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: patkarbo47/cicd-front:v1.1  # Remplacez avec votre image Docker
          ports:
            - containerPort: 80