apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000 #Port d'écoute du service
      targetPort: 8000 # Port d'écoute des Pods
  type: ClusterIP # Cluster IP n'est disponible uniquement qu'a l'interieur des cluster Kubernetes
