# Fichier de configuration Prometheus, ne pas appliquer avec apply
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'backend'
    static_configs:
    - targets: ['backend-service:8000']